Darwin/ARM64 build target (#11321)
* Update to Go 1.16.2 for build/dev

* Update SDK version_base

* 1st attempt

* Update docker images

* wip

* wip

diff --git a/.circleci/config/@build-release.yml b/.circleci/config/@build-release.yml
--- a/.circleci/config/@build-release.yml
+++ b/.circleci/config/@build-release.yml
@@ -190,6 +190,9 @@ jobs:
           key: package-a8bdeecb59f5f37dc83943709455b9fd277df5f8-{{checksum ".buildcache/cache-keys/package-a8bdeecb59f5f37dc83943709455b9fd277df5f8"}}
           name: Restore package cache
       - restore_cache:
+          key: package-6d19c35fee4eeaaa71e4d6b5d7f98a4d5284797c-{{checksum ".buildcache/cache-keys/package-6d19c35fee4eeaaa71e4d6b5d7f98a4d5284797c"}}
+          name: Restore package cache
+      - restore_cache:
           key: package-26548a1820e022c07891751a5b3d80a890a7e0d8-{{checksum ".buildcache/cache-keys/package-26548a1820e022c07891751a5b3d80a890a7e0d8"}}
           name: Restore package cache
       - restore_cache:
@@ -241,20 +244,20 @@ jobs:
           command: ls -lahR .buildcache
           name: List Build Cache
       - run:
-          command: cp packages*.lock/pkgs.yml lockfile-70f9f741143d5305.yml
+          command: cp packages*.lock/pkgs.yml lockfile-146a431e832db58c.yml
           name: Update Lockfile Name
       - run:
-          command: tar -czf packages-70f9f741143d5305.tar.gz .buildcache/packages lockfile-70f9f741143d5305.yml
+          command: tar -czf packages-146a431e832db58c.tar.gz .buildcache/packages lockfile-146a431e832db58c.yml
           name: Create Raw Package Tarball
       - run:
-          command: tar -czf meta-70f9f741143d5305.tar.gz .buildcache/packages/store/*.json lockfile-70f9f741143d5305.yml
+          command: tar -czf meta-146a431e832db58c.tar.gz .buildcache/packages/store/*.json lockfile-146a431e832db58c.yml
           name: Create Metadata Tarball
       - store_artifacts:
-          path: lockfile-70f9f741143d5305.yml
+          path: lockfile-146a431e832db58c.yml
       - store_artifacts:
-          path: packages-70f9f741143d5305.tar.gz
+          path: packages-146a431e832db58c.tar.gz
       - store_artifacts:
-          path: meta-70f9f741143d5305.tar.gz
+          path: meta-146a431e832db58c.tar.gz
       - store_artifacts:
           path: .buildcache/packages
   darwin_amd64_package:
@@ -330,6 +333,79 @@ jobs:
           name: Save package cache
     environment:
       PACKAGE_SPEC_ID: a8bdeecb59f5f37dc83943709455b9fd277df5f8
+  darwin_arm64_package:
+    executor: builder
+    steps:
+      - setup_remote_docker:
+          version: 19.03.12
+          docker_layer_caching: false
+      - add_ssh_keys:
+          fingerprints:
+            - c6:96:98:82:dc:04:6c:39:dd:ac:83:05:e3:15:1c:98
+      - checkout:
+          path: .
+      - run:
+          command: make -C packages*.lock write-package-cache-key
+          name: Write package cache key
+      - restore_cache:
+          key: package-6d19c35fee4eeaaa71e4d6b5d7f98a4d5284797c-{{checksum ".buildcache/cache-keys/package-6d19c35fee4eeaaa71e4d6b5d7f98a4d5284797c"}}
+          name: Restore package cache
+      - run:
+          command: |2
+
+            if ! { PKG=$(find .buildcache/packages/store -maxdepth 1 -mindepth 1 -name '*.zip' 2> /dev/null) && [ -n "$PKG" ]; }; then
+              echo "No package found, continuing with build."
+              exit 0
+            fi
+            echo "Package already cached, skipping build."
+            circleci-agent step halt
+          name: Check cache status
+      - run:
+          command: make -C packages*.lock write-builder-cache-keys
+          name: Write builder layer cache keys
+      - restore_cache:
+          key: copy-source_4c1e_{{checksum ".buildcache/cache-keys/copy-source-4c1ebdd7e5676d7830250c9ccb4600e937128808"}}
+          keys:
+            - warm-go-build-vendor-cache_33b0_{{checksum ".buildcache/cache-keys/warm-go-build-vendor-cache-33b04d5c76259ee7c98c82d08215552a97c76439"}}
+            - build-static-assets_9ad4_{{checksum ".buildcache/cache-keys/build-static-assets-9ad4d7bfb12bb41ea259f917763c635da5fece63"}}
+            - build-ui_3f5e_{{checksum ".buildcache/cache-keys/build-ui-3f5e0479b9b1a145c921617b0e2e0f6c05d5dd47"}}
+            - ui-dependencies_5132_{{checksum ".buildcache/cache-keys/ui-dependencies-513283a98d2b8a1570bf027e95364b888df651a9"}}
+            - install-yarn_6b98_{{checksum ".buildcache/cache-keys/install-yarn-6b98fb22387ba58bb85acb0cc5909e6b6b2dbfea"}}
+            - set-workdir_577a_{{checksum ".buildcache/cache-keys/set-workdir-577aad3893a929a48a2ce7319179c253507dee67"}}
+            - install-go-tools_a10e_{{checksum ".buildcache/cache-keys/install-go-tools-a10e38af920222100809a5d52ac413e922688b48"}}
+            - install-go_d3cf_{{checksum ".buildcache/cache-keys/install-go-d3cfbf34edb1074513e0377a86595f5e740cd03b"}}
+            - base_c6cd_{{checksum ".buildcache/cache-keys/base-c6cdf1b224722d2520e082320f2a71875913247c"}}
+          name: 'Restore Builder Image Cache: copy-source'
+      - run:
+          command: make -C packages*.lock load-builder-cache
+          name: Load whatever builder cache we have (if any) into the Docker daemon
+          no_output_timeout: 30m
+      - run:
+          command: |2-
+
+            KEYFILE="$HOME/.ssh/id_rsa_c6969882dc046c39ddac8305e3151c98"
+            eval "$(ssh-agent -s)"
+            if [ -f "$KEYFILE" ]; then
+              ssh-add "$KEYFILE"
+            else
+              echo "==> INFO: SSH key for github.com not found"
+              echo "    Attempts to access private repositories from within"
+              echo "    the build will fail, e.g. for private go modules, or"
+              echo "    attempts to directly clone private repositories."
+            fi
+
+            make -C packages*.lock package
+          name: Compile Package
+      - run:
+          command: ls -lahR .buildcache/packages
+          name: List packages
+      - save_cache:
+          paths:
+            - .buildcache/packages/store
+          key: package-6d19c35fee4eeaaa71e4d6b5d7f98a4d5284797c-{{checksum ".buildcache/cache-keys/package-6d19c35fee4eeaaa71e4d6b5d7f98a4d5284797c"}}
+          name: Save package cache
+    environment:
+      PACKAGE_SPEC_ID: 6d19c35fee4eeaaa71e4d6b5d7f98a4d5284797c
   freebsd_386_package:
     executor: builder
     steps:
@@ -1353,7 +1429,7 @@ jobs:
     environment:
       PACKAGE_SPEC_ID: 4ecc34b0623444ae14f47a9065565cd7e1f7448b
 workflows:
-  build-70f9f741143d5305:
+  build-146a431e832db58c:
     jobs:
       - build-common-layers: {}
       - darwin_amd64_package:
@@ -1362,6 +1438,7 @@ workflows:
       - bundle-releases:
           requires:
             - darwin_amd64_package
+            - darwin_arm64_package
             - freebsd_386_package
             - freebsd_amd64_package
             - freebsd_arm_package
@@ -1376,6 +1453,9 @@ workflows:
             - solaris_amd64_package
             - windows_386_package
             - windows_amd64_package
+      - darwin_arm64_package:
+          requires:
+            - build-common-layers
       - freebsd_386_package:
           requires:
             - build-common-layers
