re-enable arm64

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -22,6 +22,9 @@ jobs:
         key: package-09201dea411bc3e86b081b260c04d6a12556746b-{{checksum ".buildcache/cache-keys/package-09201dea411bc3e86b081b260c04d6a12556746b"}}
         name: Restore package cache
     - restore_cache:
+        key: package-2933907cec6381f0fefd5a8319a34a26ec26a129-{{checksum ".buildcache/cache-keys/package-2933907cec6381f0fefd5a8319a34a26ec26a129"}}
+        name: Restore package cache
+    - restore_cache:
         key: package-81a979f9c69bfdecfef2e7282dbef1e63d14beb5-{{checksum ".buildcache/cache-keys/package-81a979f9c69bfdecfef2e7282dbef1e63d14beb5"}}
         name: Restore package cache
     - restore_cache:
@@ -73,20 +76,20 @@ jobs:
         command: ls -lahR .buildcache
         name: List Build Cache
     - run:
-        command: cp packages*.lock/pkgs.yml lockfile-34323548b70551e7.yml
+        command: cp packages*.lock/pkgs.yml lockfile-f140ced297dd140.yml
         name: Update Lockfile Name
     - run:
-        command: tar -czf packages-34323548b70551e7.tar.gz .buildcache/packages lockfile-34323548b70551e7.yml
+        command: tar -czf packages-f140ced297dd140.tar.gz .buildcache/packages lockfile-f140ced297dd140.yml
         name: Create Raw Package Tarball
     - run:
-        command: tar -czf meta-34323548b70551e7.tar.gz .buildcache/packages/store/*.json lockfile-34323548b70551e7.yml
+        command: tar -czf meta-f140ced297dd140.tar.gz .buildcache/packages/store/*.json lockfile-f140ced297dd140.yml
         name: Create Metadata Tarball
     - store_artifacts:
-        path: lockfile-34323548b70551e7.yml
+        path: lockfile-f140ced297dd140.yml
     - store_artifacts:
-        path: packages-34323548b70551e7.tar.gz
+        path: packages-f140ced297dd140.tar.gz
     - store_artifacts:
-        path: meta-34323548b70551e7.tar.gz
+        path: meta-f140ced297dd140.tar.gz
     - store_artifacts:
         path: .buildcache/packages
     environment:
@@ -168,6 +171,84 @@ jobs:
         name: List packages
     - save_cache:
         key: package-09201dea411bc3e86b081b260c04d6a12556746b-{{checksum ".buildcache/cache-keys/package-09201dea411bc3e86b081b260c04d6a12556746b"}}
+        name: Save package cache
+        paths:
+        - .buildcache/packages/store
+  darwin_arm64_package:
+    docker:
+    - image: docker.mirror.hashicorp.services/circleci/buildpack-deps
+    shell: /usr/bin/env bash -euo pipefail -c
+    environment:
+    - AUTO_INSTALL_TOOLS: 'YES'
+    - BUILDKIT_PROGRESS: plain
+    - PRODUCT_REVISION: ''
+    - PACKAGE_SPEC_ID: 2933907cec6381f0fefd5a8319a34a26ec26a129
+    steps:
+    - setup_remote_docker:
+        docker_layer_caching: false
+        version: 19.03.12
+    - add_ssh_keys:
+        fingerprints:
+        - c6:96:98:82:dc:04:6c:39:dd:ac:83:05:e3:15:1c:98
+    - checkout:
+        path: .
+    - run:
+        command: make -C packages*.lock write-package-cache-key
+        name: Write package cache key
+    - restore_cache:
+        key: package-2933907cec6381f0fefd5a8319a34a26ec26a129-{{checksum ".buildcache/cache-keys/package-2933907cec6381f0fefd5a8319a34a26ec26a129"}}
+        name: Restore package cache
+    - run:
+        command: |2
+
+          if ! { PKG=$(find .buildcache/packages/store -maxdepth 1 -mindepth 1 -name '*.zip' 2> /dev/null) && [ -n "$PKG" ]; }; then
+            echo "No package found, continuing with build."
+            exit 0
+          fi
+          echo "Package already cached, skipping build."
+          circleci-agent step halt
+        name: Check cache status
+    - run:
+        command: make -C packages*.lock write-builder-cache-keys
+        name: Write builder layer cache keys
+    - restore_cache:
+        key: copy-source_f088_{{checksum ".buildcache/cache-keys/copy-source-f08876e17d04722a59c7915a09faf71c1426359b"}}
+        keys:
+        - warm-go-build-vendor-cache_0d1c_{{checksum ".buildcache/cache-keys/warm-go-build-vendor-cache-0d1c85fca0f39d67b2203b21f0aa73d01ed51787"}}
+        - build-ui_b996_{{checksum ".buildcache/cache-keys/build-ui-b996512e806437efb2e3e12754a2bb710994e091"}}
+        - ui-dependencies_eb1b_{{checksum ".buildcache/cache-keys/ui-dependencies-eb1bff3a8a4ed97aef1e99c594b616da9f2de6f6"}}
+        - make-ui-folder_ecfd_{{checksum ".buildcache/cache-keys/make-ui-folder-ecfd4315a398276c29eb15fa0b3f36e5bd9a30c5"}}
+        - install-yarn_9f11_{{checksum ".buildcache/cache-keys/install-yarn-9f110a2979fbd0dc375c1becf68a9801978895f9"}}
+        - set-workdir_74c4_{{checksum ".buildcache/cache-keys/set-workdir-74c461ee3a5be172c9e8ea7cabe1a2432e773a11"}}
+        - install-go-tools_296d_{{checksum ".buildcache/cache-keys/install-go-tools-296d5f79732a9d8ef4a1a59cb6cdbd30ac6f3f1a"}}
+        - install-go_d3cf_{{checksum ".buildcache/cache-keys/install-go-d3cfbf34edb1074513e0377a86595f5e740cd03b"}}
+        - base_c6cd_{{checksum ".buildcache/cache-keys/base-c6cdf1b224722d2520e082320f2a71875913247c"}}
+        name: 'Restore Builder Image Cache: copy-source'
+    - run:
+        command: make -C packages*.lock load-builder-cache
+        name: Load whatever builder cache we have (if any) into the Docker daemon
+        no_output_timeout: 30m
+    - run:
+        command: |2-
+
+          KEYFILE="$HOME/.ssh/id_rsa_c6969882dc046c39ddac8305e3151c98"
+          eval "$(ssh-agent -s)"
+          if [ -f "$KEYFILE" ]; then
+            ssh-add "$KEYFILE"
+          else
+            echo "==> INFO: SSH key for github.com not found"
+            echo "    Attempts to access private repositories from within"
+            echo "    the build will fail, e.g. for private go modules, or"
+            echo "    attempts to directly clone private repositories."
+          fi
+
+          make -C packages*.lock package
+        name: Compile Package
+    - run:
+        command: ls -lahR .buildcache/packages
+        name: List packages
+    - save_cache:
+        key: package-2933907cec6381f0fefd5a8319a34a26ec26a129-{{checksum ".buildcache/cache-keys/package-2933907cec6381f0fefd5a8319a34a26ec26a129"}}
         name: Save package cache
         paths:
         - .buildcache/packages/store
@@ -2347,7 +2428,7 @@ jobs:
     - GO_TAGS: ''
     - GO111MODULE: 'off'
 workflows:
-  build-34323548b70551e7:
+  build-f140ced297dd140:
     jobs:
     - build-common-layers
     - darwin_amd64_package:
@@ -2356,6 +2437,7 @@ workflows:
     - bundle-releases:
         requires:
         - darwin_amd64_package
+        - darwin_arm64_package
         - freebsd_386_package
         - freebsd_amd64_package
         - freebsd_arm_package
@@ -2370,6 +2452,9 @@ workflows:
         - solaris_amd64_package
         - windows_386_package
         - windows_amd64_package
+    - darwin_arm64_package:
+        requires:
+        - build-common-layers
     - freebsd_386_package:
         requires:
         - build-common-layers
