ci: add pre-flight checks
- Right now just validates ci config is up to date.

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -1,6 +1,36 @@
-### Generated by 'make ci-config' do not manually edit this file.
+### Generated by 'make ci-config' do not manually edit this file. 
 version: 2
 jobs:
+  pre-flight-checks:
+    docker:
+    - image: circleci/buildpack-deps
+    environment:
+    - PATH_EXTRA: /tmp/circleci
+    steps:
+    - checkout
+    - run:
+        command: |
+          set -x
+          mkdir -p $PATH_EXTRA
+          export PATH="$PATH_EXTRA:$PATH"
+          NAME=circleci-cli_${VERSION}_${ARCH}
+          URL=$BASE/v${VERSION}/${NAME}.tar.gz
+          curl -sSL $URL \
+            | tar --overwrite --strip-components=1 -xz -C $PATH_EXTRA "${NAME}/circleci"
+          which circleci
+          circleci version
+        environment:
+          ARCH: linux_amd64
+          BASE: https://github.com/CircleCI-Public/circleci-cli/releases/download
+          VERSION: 0.1.5691
+        name: Install CircleCI CLI
+        shell: /usr/bin/env bash -euo pipefail
+    - run:
+        command: |
+          set -x
+          export PATH="$PATH_EXTRA:$PATH"
+          make ci-verify
+        name: make ci-verify
   install-ui-dependencies:
     docker:
     - image: node:10-stretch
@@ -250,8 +280,13 @@ jobs:
 workflows:
   ci:
     jobs:
-    - install-ui-dependencies
-    - go-mod-download
+    - pre-flight-checks
+    - install-ui-dependencies:
+        requires:
+        - pre-flight-checks
+    - go-mod-download:
+        requires:
+        - pre-flight-checks
     - build-go-dev:
         requires:
         - go-mod-download
@@ -413,6 +448,37 @@ workflows:
 #           npm rebuild node-sass
 #         name: Install UI dependencies
 #     - save_yarn_cache
+#   pre-flight-checks:
+#     description: Ensures nothing obvious is broken for faster failures.
+#     docker:
+#     - image: circleci/buildpack-deps
+#     environment:
+#       PATH_EXTRA: /tmp/circleci
+#     steps:
+#     - checkout
+#     - run:
+#         command: |
+#           set -x
+#           mkdir -p $PATH_EXTRA
+#           export PATH=\"$PATH_EXTRA:$PATH\"
+#           NAME=circleci-cli_${VERSION}_${ARCH}
+#           URL=$BASE/v${VERSION}/${NAME}.tar.gz
+#           curl -sSL $URL \\
+#             | tar --overwrite --strip-components=1 -xz -C $PATH_EXTRA \"${NAME}/circleci\"
+#           which circleci
+#           circleci version
+#         environment:
+#           ARCH: linux_amd64
+#           BASE: https://github.com/CircleCI-Public/circleci-cli/releases/download
+#           VERSION: 0.1.5691
+#         name: Install CircleCI CLI
+#         shell: /usr/bin/env bash -euo pipefail
+#     - run:
+#         command: |
+#           set -x
+#           export PATH=\"$PATH_EXTRA:$PATH\"
+#           make ci-verify
+#         name: make ci-verify
 #   test-go:
 #     executor: go-machine
 #     parallelism: 2
@@ -494,8 +560,13 @@ workflows:
 # workflows:
 #   ci:
 #     jobs:
-#     - install-ui-dependencies
-#     - go-mod-download
+#     - pre-flight-checks
+#     - install-ui-dependencies:
+#         requires:
+#         - pre-flight-checks
+#     - go-mod-download:
+#         requires:
+#         - pre-flight-checks
 #     - build-go-dev:
 #         requires:
 #         - go-mod-download
