ci: disable git diff pager

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -2189,11 +2189,8 @@ jobs:
         name: go mod download
     - run:
         command: |
-          git diff --exit-code || {
-            echo "Files modified:"
-            git diff --name-only
-            echo "Contents:"
-            git diff
+          git diff --no-pager --exit-code || {
+            echo "ERROR: Files modified by go mod download, see above."
             exit 1
           }
         name: Verify downloading modules did not modify any files
diff --git a/.circleci/config/commands/@yarn-cache.yml b/.circleci/config/commands/@yarn-cache.yml
--- a/.circleci/config/commands/@yarn-cache.yml
+++ b/.circleci/config/commands/@yarn-cache.yml
@@ -33,11 +33,8 @@ refresh_go_mod_cache:
     - run:
         name: Verify downloading modules did not modify any files
         command: |
-          git diff --exit-code || {
-            echo "Files modified:"
-            git diff --name-only
-            echo "Contents:"
-            git diff
+          git diff --no-pager --exit-code || {
+            echo "ERROR: Files modified by go mod download, see above."
             exit 1
           }
     - save_go_mod_cache
