updating .circleci

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -685,7 +685,7 @@ jobs:
     environment:
     - CIRCLECI_CLI_VERSION: 0.1.5546
     - GO_TAGS: ''
-    - GO_VERSION: 1.15.7
+    - GO_VERSION: 1.16.2
     - GO111MODULE: 'off'
     - GOTESTSUM_VERSION: 0.5.2
   algolia-index:
@@ -783,7 +783,7 @@ jobs:
         - .buildcache/packages/store
   test-go-remote-docker:
     docker:
-    - image: docker.mirror.hashicorp.services/circleci/golang:1.15.4-buster
+    - image: docker.mirror.hashicorp.services/circleci/golang:1.16.2-buster
     resource_class: medium
     working_directory: /go/src/github.com/hashicorp/vault
     parallelism: 8
@@ -803,6 +803,13 @@ jobs:
     - setup_remote_docker:
         docker_layer_caching: true
         version: 18.09.3
+    - run:
+        command: |
+          TZ=GMT date '+%Y%m%d' > /tmp/go-cache-key
+        name: Compute test cache key
+    - restore_cache:
+        keys:
+        - go-test-cache-date-v1-{{ checksum "/tmp/go-cache-key" }}
     - run:
         command: |
           set -x
@@ -864,16 +871,17 @@ jobs:
               -e DOCKER_CERT_PATH -e DOCKER_HOST -e DOCKER_MACHINE_NAME -e DOCKER_TLS_VERIFY -e NO_PROXY \
               -e VAULT_TEST_LOG_DIR=/tmp/testlogs \
               --network vaulttest --name \
-              testcontainer circleci/golang:1.15.4-buster \
+              testcontainer docker.mirror.hashicorp.services/circleci/golang:1.15.11-buster \
               tail -f /dev/null
 
             # Run tests
+            test -d /tmp/go-cache && docker cp /tmp/go-cache testcontainer:/tmp/gocache
             docker exec testcontainer sh -c 'mkdir -p /go/src/github.com/hashicorp/vault'
             docker cp . testcontainer:/go/src/github.com/hashicorp/vault/
             docker cp $DOCKER_CERT_PATH/ testcontainer:$DOCKER_CERT_PATH
 
             docker exec -w /go/src/github.com/hashicorp/vault/ \
-              -e GO111MODULE -e CIRCLECI -e VAULT_CI_GO_TEST_RACE \
+              -e GO111MODULE -e CIRCLECI -e GOCACHE=/tmp/gocache -e VAULT_CI_GO_TEST_RACE \
               testcontainer \
               gotestsum --format=short-verbose \
                 --junitfile test-results/go-test/results.xml \
@@ -885,21 +893,23 @@ jobs:
                  \
                 ${package_names}
           else
-            gotestsum --format=short-verbose \
-              --junitfile test-results/go-test/results.xml \
-              --jsonfile test-results/go-test/results.json \
-              -- \
-              -tags "${GO_TAGS}" \
-              -timeout=60m \
-              -parallel=20 \
-               \
-              ${package_names}
+            GOCACHE=/tmp/go-cache \
+              gotestsum --format=short-verbose \
+                --junitfile test-results/go-test/results.xml \
+                --jsonfile test-results/go-test/results.json \
+                -- \
+                -tags "${GO_TAGS}" \
+                -timeout=60m \
+                -parallel=20 \
+                 \
+                ${package_names}
           fi
         name: Run Go tests
         no_output_timeout: 60m
     - run:
         command: |
           docker cp testcontainer:/go/src/github.com/hashicorp/vault/test-results .
+          docker cp testcontainer:/tmp/gocache /tmp/go-cache
         name: Copy test results
         when: always
     - store_artifacts:
@@ -992,7 +1002,7 @@ jobs:
         - .buildcache/packages/store
   test-go-race:
     docker:
-    - image: docker.mirror.hashicorp.services/circleci/golang:1.15.4-buster
+    - image: docker.mirror.hashicorp.services/circleci/golang:1.16.2-buster
     resource_class: xlarge
     working_directory: /go/src/github.com/hashicorp/vault
     parallelism: 8
@@ -1009,6 +1019,13 @@ jobs:
         name: Check branch name
         working_directory: ~/
     - checkout
+    - run:
+        command: |
+          TZ=GMT date '+%Y%m%d' > /tmp/go-cache-key
+        name: Compute test cache key
+    - restore_cache:
+        keys:
+        - go-test-cache-date-v1-{{ checksum "/tmp/go-cache-key" }}
     - run:
         command: |
           set -x
@@ -1069,16 +1086,17 @@ jobs:
               -e DOCKER_CERT_PATH -e DOCKER_HOST -e DOCKER_MACHINE_NAME -e DOCKER_TLS_VERIFY -e NO_PROXY \
               -e VAULT_TEST_LOG_DIR=/tmp/testlogs \
               --network vaulttest --name \
-              testcontainer circleci/golang:1.15.4-buster \
+              testcontainer docker.mirror.hashicorp.services/circleci/golang:1.15.11-buster \
               tail -f /dev/null
 
             # Run tests
+            test -d /tmp/go-cache && docker cp /tmp/go-cache testcontainer:/tmp/gocache
             docker exec testcontainer sh -c 'mkdir -p /go/src/github.com/hashicorp/vault'
             docker cp . testcontainer:/go/src/github.com/hashicorp/vault/
             docker cp $DOCKER_CERT_PATH/ testcontainer:$DOCKER_CERT_PATH
 
             docker exec -w /go/src/github.com/hashicorp/vault/ \
-              -e GO111MODULE -e CIRCLECI -e VAULT_CI_GO_TEST_RACE \
+              -e GO111MODULE -e CIRCLECI -e GOCACHE=/tmp/gocache -e VAULT_CI_GO_TEST_RACE \
               testcontainer \
               gotestsum --format=short-verbose \
                 --junitfile test-results/go-test/results.xml \
@@ -1090,15 +1108,16 @@ jobs:
                 -race \
                 ${package_names}
           else
-            gotestsum --format=short-verbose \
-              --junitfile test-results/go-test/results.xml \
-              --jsonfile test-results/go-test/results.json \
-              -- \
-              -tags "${GO_TAGS}" \
-              -timeout=60m \
-              -parallel=20 \
-              -race \
-              ${package_names}
+            GOCACHE=/tmp/go-cache \
+              gotestsum --format=short-verbose \
+                --junitfile test-results/go-test/results.xml \
+                --jsonfile test-results/go-test/results.json \
+                -- \
+                -tags "${GO_TAGS}" \
+                -timeout=60m \
+                -parallel=20 \
+                -race \
+                ${package_names}
           fi
         name: Run Go tests
         no_output_timeout: 60m
@@ -1449,7 +1468,7 @@ jobs:
         - .buildcache/packages/store
   test-go:
     docker:
-    - image: docker.mirror.hashicorp.services/circleci/golang:1.15.4-buster
+    - image: docker.mirror.hashicorp.services/circleci/golang:1.16.2-buster
     resource_class: large
     working_directory: /go/src/github.com/hashicorp/vault
     parallelism: 8
@@ -1466,6 +1485,13 @@ jobs:
         name: Check branch name
         working_directory: ~/
     - checkout
+    - run:
+        command: |
+          TZ=GMT date '+%Y%m%d' > /tmp/go-cache-key
+        name: Compute test cache key
+    - restore_cache:
+        keys:
+        - go-test-cache-date-v1-{{ checksum "/tmp/go-cache-key" }}
     - run:
         command: |
           set -x
@@ -1526,16 +1552,17 @@ jobs:
               -e DOCKER_CERT_PATH -e DOCKER_HOST -e DOCKER_MACHINE_NAME -e DOCKER_TLS_VERIFY -e NO_PROXY \
               -e VAULT_TEST_LOG_DIR=/tmp/testlogs \
               --network vaulttest --name \
-              testcontainer circleci/golang:1.15.4-buster \
+              testcontainer docker.mirror.hashicorp.services/circleci/golang:1.15.11-buster \
               tail -f /dev/null
 
             # Run tests
+            test -d /tmp/go-cache && docker cp /tmp/go-cache testcontainer:/tmp/gocache
             docker exec testcontainer sh -c 'mkdir -p /go/src/github.com/hashicorp/vault'
             docker cp . testcontainer:/go/src/github.com/hashicorp/vault/
             docker cp $DOCKER_CERT_PATH/ testcontainer:$DOCKER_CERT_PATH
 
             docker exec -w /go/src/github.com/hashicorp/vault/ \
-              -e GO111MODULE -e CIRCLECI -e VAULT_CI_GO_TEST_RACE \
+              -e GO111MODULE -e CIRCLECI -e GOCACHE=/tmp/gocache -e VAULT_CI_GO_TEST_RACE \
               testcontainer \
               gotestsum --format=short-verbose \
                 --junitfile test-results/go-test/results.xml \
@@ -1547,15 +1574,16 @@ jobs:
                  \
                 ${package_names}
           else
-            gotestsum --format=short-verbose \
-              --junitfile test-results/go-test/results.xml \
-              --jsonfile test-results/go-test/results.json \
-              -- \
-              -tags "${GO_TAGS}" \
-              -timeout=60m \
-              -parallel=20 \
-               \
-              ${package_names}
+            GOCACHE=/tmp/go-cache \
+              gotestsum --format=short-verbose \
+                --junitfile test-results/go-test/results.xml \
+                --jsonfile test-results/go-test/results.json \
+                -- \
+                -tags "${GO_TAGS}" \
+                -timeout=60m \
+                -parallel=20 \
+                 \
+                ${package_names}
           fi
         name: Run Go tests
         no_output_timeout: 60m
@@ -1569,6 +1597,159 @@ jobs:
     - CIRCLECI_CLI_VERSION: 0.1.5546
     - GO_TAGS: ''
     - GO111MODULE: 'off'
+  test-go-nightly:
+    machine: true
+    shell: /usr/bin/env bash -euo pipefail -c
+    working_directory: /go/src/github.com/hashicorp/vault
+    steps:
+    - run:
+        command: |
+          # If the branch being tested starts with ui/ or docs/ we want to exit the job without failing
+          [[ "$CIRCLE_BRANCH" = ui/* || "$CIRCLE_BRANCH" = docs/* ]] && {
+            # stop the job from this step
+            circleci-agent step halt
+          }
+          # exit with success either way
+          exit 0
+        name: Check branch name
+        working_directory: ~/
+    - run:
+        command: |
+          [ -n "$GO_VERSION" ] || { echo "You must set GO_VERSION"; exit 1; }
+          # Install Go
+          curl -sSLO "https://dl.google.com/go/go${GO_VERSION}.linux-amd64.tar.gz"
+          sudo rm -rf /usr/local/go
+          sudo tar -C /usr/local -xzf "go${GO_VERSION}.linux-amd64.tar.gz"
+          rm -f "go${GO_VERSION}.linux-amd64.tar.gz"
+          GOPATH="/go"
+          mkdir $GOPATH 2>/dev/null || { sudo mkdir $GOPATH && sudo chmod 777 $GOPATH; }
+          echo "export GOPATH='$GOPATH'" >> "$BASH_ENV"
+          echo "export PATH='$PATH:$GOPATH/bin:/usr/local/go/bin'" >> "$BASH_ENV"
+
+          echo "$ go version"
+          go version
+        name: Setup Go
+        working_directory: ~/
+    - checkout
+    - run:
+        command: |
+          TZ=GMT date '+%Y%m%d' > /tmp/go-cache-key
+        name: Compute test cache key
+    - restore_cache:
+        keys:
+        - go-test-cache-date-v1-{{ checksum "/tmp/go-cache-key" }}
+    - run:
+        command: |
+          set -x
+
+          case "" in
+          *-race*) export VAULT_CI_GO_TEST_RACE=1;;
+          esac
+
+          # Install CircleCI CLI
+          curl -sSL \
+              "https://github.com/CircleCI-Public/circleci-cli/releases/download/v${CIRCLECI_CLI_VERSION}/circleci-cli_${CIRCLECI_CLI_VERSION}_linux_amd64.tar.gz" \
+            | sudo tar --overwrite -xz \
+              -C /usr/local/bin \
+              "circleci-cli_${CIRCLECI_CLI_VERSION}_linux_amd64/circleci"
+
+          USE_DOCKER=0
+
+          # Split Go tests by prior test times.  If use_docker is true, only run
+          # tests that depend on docker, otherwise only those that don't.
+          if [ $USE_DOCKER == 1 ]; then
+            package_names=$(go list -test -json ./... |
+              jq -r 'select(.Deps != null) |
+                select(any(.Deps[] ; contains("github.com/hashicorp/vault/helper/testhelpers/docker"))) |
+                .ForTest | select(. != null)' |
+                sort -u | circleci tests split --split-by=timings --timings-type=classname)
+          else
+            package_names=$(go list -test -json ./... |
+              jq -r 'select(.Deps != null) |
+                select(all(.Deps[] ; contains("github.com/hashicorp/vault/helper/testhelpers/docker")|not)) |
+                .ForTest | select(. != null)' |
+                sort -u | circleci tests split --split-by=timings --timings-type=classname)
+          fi
+
+          # After running tests split step, we are now running the following steps
+          # in multiple different containers, each getting a different subset of
+          # the test packages in their package_names variable.  Each container
+          # has its own remote docker VM.
+
+          make prep
+          mkdir -p test-results/go-test
+
+          # Create a docker network for our testcontainer
+          if [ $USE_DOCKER == 1 ]; then
+            # Despite the fact that we're using a circleci image (thus getting the
+            # version they chose for the docker cli) and that we're specifying a
+            # docker version to use for the remote docker instances, we occasionally
+            # see "client version too new, max supported version 1.39" errors for
+            # reasons unclear.
+            export DOCKER_API_VERSION=1.39
+
+            export TEST_DOCKER_NETWORK_ID=$(docker network list -q -f 'name=vaulttest')
+            if [ -z $TEST_DOCKER_NETWORK_ID ]; then
+              TEST_DOCKER_NETWORK_ID=$(docker network create vaulttest)
+            fi
+
+            # Start a docker testcontainer to run the tests in
+            docker run -d -e TEST_DOCKER_NETWORK_ID \
+              -e DOCKER_CERT_PATH -e DOCKER_HOST -e DOCKER_MACHINE_NAME -e DOCKER_TLS_VERIFY -e NO_PROXY \
+              -e VAULT_TEST_LOG_DIR=/tmp/testlogs \
+              --network vaulttest --name \
+              testcontainer docker.mirror.hashicorp.services/circleci/golang:1.15.11-buster \
+              tail -f /dev/null
+
+            # Run tests
+            test -d /tmp/go-cache && docker cp /tmp/go-cache testcontainer:/tmp/gocache
+            docker exec testcontainer sh -c 'mkdir -p /go/src/github.com/hashicorp/vault'
+            docker cp . testcontainer:/go/src/github.com/hashicorp/vault/
+            docker cp $DOCKER_CERT_PATH/ testcontainer:$DOCKER_CERT_PATH
+
+            docker exec -w /go/src/github.com/hashicorp/vault/ \
+              -e GO111MODULE -e CIRCLECI -e GOCACHE=/tmp/gocache -e VAULT_CI_GO_TEST_RACE \
+              testcontainer \
+              gotestsum --format=short-verbose \
+                --junitfile test-results/go-test/results.xml \
+                --jsonfile test-results/go-test/results.json \
+                -- \
+                -tags "${GO_TAGS}" \
+                -timeout=60m \
+                -parallel=20 \
+                 \
+                ${package_names}
+          else
+            GOCACHE=/tmp/go-cache \
+              gotestsum --format=short-verbose \
+                --junitfile test-results/go-test/results.xml \
+                --jsonfile test-results/go-test/results.json \
+                -- \
+                -tags "${GO_TAGS}" \
+                -timeout=60m \
+                -parallel=20 \
+                 \
+                ${package_names}
+          fi
+        name: Run Go tests
+        no_output_timeout: 60m
+    - save_cache:
+        key: go-test-cache-date-v1-{{ checksum "/tmp/go-cache-key" }}
+        paths:
+        - /tmp/go-cache
+        when: always
+    - store_artifacts:
+        path: test-results
+    - store_test_results:
+        path: test-results
+    - store_artifacts:
+        path: /tmp/testlogs
+    environment:
+    - CIRCLECI_CLI_VERSION: 0.1.5546
+    - GO_TAGS: ''
+    - GO_VERSION: 1.16.2
+    - GO111MODULE: 'off'
+    - GOTESTSUM_VERSION: 0.5.2
   netbsd_amd64_package:
     docker:
     - image: docker.mirror.hashicorp.services/circleci/buildpack-deps
@@ -2021,12 +2202,12 @@ jobs:
     environment:
     - CIRCLECI_CLI_VERSION: 0.1.5546
     - GO_TAGS: ''
-    - GO_VERSION: 1.15.7
+    - GO_VERSION: 1.16.2
     - GO111MODULE: 'off'
     - GOTESTSUM_VERSION: 0.5.2
   test-go-race-remote-docker:
     docker:
-    - image: docker.mirror.hashicorp.services/circleci/golang:1.15.4-buster
+    - image: docker.mirror.hashicorp.services/circleci/golang:1.16.2-buster
     resource_class: medium
     working_directory: /go/src/github.com/hashicorp/vault
     parallelism: 8
@@ -2046,6 +2227,13 @@ jobs:
     - setup_remote_docker:
         docker_layer_caching: true
         version: 18.09.3
+    - run:
+        command: |
+          TZ=GMT date '+%Y%m%d' > /tmp/go-cache-key
+        name: Compute test cache key
+    - restore_cache:
+        keys:
+        - go-test-cache-date-v1-{{ checksum "/tmp/go-cache-key" }}
     - run:
         command: |
           set -x
@@ -2107,16 +2295,17 @@ jobs:
               -e DOCKER_CERT_PATH -e DOCKER_HOST -e DOCKER_MACHINE_NAME -e DOCKER_TLS_VERIFY -e NO_PROXY \
               -e VAULT_TEST_LOG_DIR=/tmp/testlogs \
               --network vaulttest --name \
-              testcontainer circleci/golang:1.15.4-buster \
+              testcontainer docker.mirror.hashicorp.services/circleci/golang:1.15.11-buster \
               tail -f /dev/null
 
             # Run tests
+            test -d /tmp/go-cache && docker cp /tmp/go-cache testcontainer:/tmp/gocache
             docker exec testcontainer sh -c 'mkdir -p /go/src/github.com/hashicorp/vault'
             docker cp . testcontainer:/go/src/github.com/hashicorp/vault/
             docker cp $DOCKER_CERT_PATH/ testcontainer:$DOCKER_CERT_PATH
 
             docker exec -w /go/src/github.com/hashicorp/vault/ \
-              -e GO111MODULE -e CIRCLECI -e VAULT_CI_GO_TEST_RACE \
+              -e GO111MODULE -e CIRCLECI -e GOCACHE=/tmp/gocache -e VAULT_CI_GO_TEST_RACE \
               testcontainer \
               gotestsum --format=short-verbose \
                 --junitfile test-results/go-test/results.xml \
@@ -2128,21 +2317,23 @@ jobs:
                 -race \
                 ${package_names}
           else
-            gotestsum --format=short-verbose \
-              --junitfile test-results/go-test/results.xml \
-              --jsonfile test-results/go-test/results.json \
-              -- \
-              -tags "${GO_TAGS}" \
-              -timeout=60m \
-              -parallel=20 \
-              -race \
-              ${package_names}
+            GOCACHE=/tmp/go-cache \
+              gotestsum --format=short-verbose \
+                --junitfile test-results/go-test/results.xml \
+                --jsonfile test-results/go-test/results.json \
+                -- \
+                -tags "${GO_TAGS}" \
+                -timeout=60m \
+                -parallel=20 \
+                -race \
+                ${package_names}
           fi
         name: Run Go tests
         no_output_timeout: 60m
     - run:
         command: |
           docker cp testcontainer:/go/src/github.com/hashicorp/vault/test-results .
+          docker cp testcontainer:/tmp/gocache /tmp/go-cache
         name: Copy test results
         when: always
     - store_artifacts:
@@ -2278,4 +2469,15 @@ workflows:
             only:
             - stable-website
         context: vault-docs
+  nightly-cachebuilder:
+    jobs:
+    - pre-flight-checks
+    - test-go-nightly
+    triggers:
+    - schedule:
+        cron: 0 9 * * *
+        filters:
+          branches:
+            only:
+            - master
   version: 2
