Replace browserstack with testem runner

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -79,25 +79,84 @@ jobs:
         path: ui/test-results
     - store_test_results:
         path: ui/test-results
-  test-ui-browserstack:
+  linux_arm_package:
     docker:
-    - image: docker.mirror.hashicorp.services/node:14-buster
+    - image: docker.mirror.hashicorp.services/circleci/buildpack-deps
     shell: /usr/bin/env bash -euo pipefail -c
-    working_directory: /go/src/github.com/hashicorp/vault
-    resource_class: xlarge
+    environment:
+    - AUTO_INSTALL_TOOLS: 'YES'
+    - BUILDKIT_PROGRESS: plain
+    - PRODUCT_REVISION: ''
+    - PACKAGE_SPEC_ID: 2cb1d35768c2d22815195653b679a1100f3812fe
     steps:
-    - checkout
-    - restore_cache:
-        key: yarn-lock-v6-{{ checksum "ui/yarn.lock" }}
-        name: Restore yarn cache
-    - attach_workspace:
-        at: .
+    - setup_remote_docker:
+        docker_layer_caching: false
+        version: 19.03.12
+    - add_ssh_keys:
+        fingerprints:
+        - 0e:03:77:f4:e2:c3:56:c2:53:6a:03:e1:31:91:2f:06
+    - checkout:
+        path: .
     - run:
-        command: |
-          # Add ./bin to the PATH so vault binary can be found.
-          export PATH="${PWD}"/bin:${PATH}
-          make test-ui-browserstack
-        name: Run Browserstack Tests
+        command: make -C packages*.lock write-package-cache-key
+        name: Write package cache key
+    - restore_cache:
+        key: package-2cb1d35768c2d22815195653b679a1100f3812fe-{{checksum ".buildcache/cache-keys/package-2cb1d35768c2d22815195653b679a1100f3812fe"}}
+        name: Restore package cache
+    - run:
+        command: |2
+
+          if ! { PKG=$(find .buildcache/packages/store -maxdepth 1 -mindepth 1 -name '*.zip' 2> /dev/null) && [ -n "$PKG" ]; }; then
+            echo "No package found, continuing with build."
+            exit 0
+          fi
+          echo "Package already cached, skipping build."
+          circleci-agent step halt
+        name: Check cache status
+    - run:
+        command: make -C packages*.lock write-builder-cache-keys
+        name: Write builder layer cache keys
+    - restore_cache:
+        key: copy-source_1ab1_{{checksum ".buildcache/cache-keys/copy-source-1ab15aacac6a43f8c71defb28e9bcdefafcecfc5"}}
+        keys:
+        - go-modules_a1e9_{{checksum ".buildcache/cache-keys/go-modules-a1e9cc6c22e8691bbc9a3bb3e91eb05d5e97730b"}}
+        - build-ui_9a4c_{{checksum ".buildcache/cache-keys/build-ui-9a4c8178808477469c37460df34f28cade634794"}}
+        - ui-dependencies_ee1b_{{checksum ".buildcache/cache-keys/ui-dependencies-ee1bc43cc876b6ac95b30d77c726ccd15ad8e4de"}}
+        - make-ui-folder_c9af_{{checksum ".buildcache/cache-keys/make-ui-folder-c9af5b6ad4a1e4dffbb201bf29c492e6a838ff43"}}
+        - install-yarn_f8c6_{{checksum ".buildcache/cache-keys/install-yarn-f8c6e065673e6047441a051da1a992019ca43a86"}}
+        - set-workdir_56f0_{{checksum ".buildcache/cache-keys/set-workdir-56f07806a01db8130a01fdbad631a2cba3ff7c53"}}
+        - install-go-tools_f4c1_{{checksum ".buildcache/cache-keys/install-go-tools-f4c1518e9671005726e8bf75513528512b36f5a2"}}
+        - install-go_877b_{{checksum ".buildcache/cache-keys/install-go-877bac5144c973403bc3944c0a4d0e870fbbb079"}}
+        - base_fc1f_{{checksum ".buildcache/cache-keys/base-fc1fa0c0d0643b393dfc77cbd78580b60fc4366f"}}
+        name: 'Restore Builder Image Cache: copy-source'
+    - run:
+        command: make -C packages*.lock load-builder-cache
+        name: Load whatever builder cache we have (if any) into the Docker daemon
+        no_output_timeout: 30m
+    - run:
+        command: |2-
+
+          KEYFILE="$HOME/.ssh/id_rsa_0e0377f4e2c356c2536a03e131912f06"
+          eval "$(ssh-agent -s)"
+          if [ -f "$KEYFILE" ]; then
+            ssh-add "$KEYFILE"
+          else
+            echo "==> INFO: SSH key for github.com not found"
+            echo "    Attempts to access private repositories from within"
+            echo "    the build will fail, e.g. for private go modules, or"
+            echo "    attempts to directly clone private repositories."
+          fi
+
+          make -C packages*.lock package
+        name: Compile Package
+    - run:
+        command: ls -lahR .buildcache/packages
+        name: List packages
+    - save_cache:
+        key: package-2cb1d35768c2d22815195653b679a1100f3812fe-{{checksum ".buildcache/cache-keys/package-2cb1d35768c2d22815195653b679a1100f3812fe"}}
+        name: Save package cache
+        paths:
+        - .buildcache/packages/store
   build-go-dev:
     machine: true
     shell: /usr/bin/env bash -euo pipefail -c
@@ -1052,7 +1111,7 @@ workflows:
         requires:
         - install-ui-dependencies
         - build-go-dev
-    - test-ui-browserstack:
+    - test-ui-browsers:
         filters:
           branches:
             ignore: /pull\/[0-9]+/
