Try splitting out the docker-dependent tests, since setting up a remote docker can be time consuming.

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -4,35 +4,6 @@
 ### ***
 version: 2
 jobs:
-  pre-flight-checks:
-    docker:
-    - image: circleci/buildpack-deps
-    environment:
-    - CCI_VERSION: 0.1.5691
-    shell: /usr/bin/env bash -euo pipefail
-    steps:
-    - checkout
-    - run:
-        command: |
-          export CCI_PATH=/tmp/circleci-cli/$CCI_VERSION
-          mkdir -p $CCI_PATH
-          NAME=circleci-cli_${CCI_VERSION}_${ARCH}
-          URL=$BASE/v${CCI_VERSION}/${NAME}.tar.gz
-          curl -sSL $URL \
-            | tar --overwrite --strip-components=1 -xz -C $CCI_PATH "${NAME}/circleci"
-          # Add circleci to the path for subsequent steps.
-          echo "export PATH=$CCI_PATH:\$PATH" >> $BASH_ENV
-          # Done, print some debug info.
-          set -x
-          . $BASH_ENV
-          which circleci
-          circleci version
-        environment:
-          ARCH: linux_amd64
-          BASE: https://github.com/CircleCI-Public/circleci-cli/releases/download
-        name: Install CircleCI CLI
-    - run:
-        command: make ci-verify
   install-ui-dependencies:
     docker:
     - environment:
@@ -54,50 +25,6 @@ jobs:
         key: yarn-lock-v6-{{ checksum "ui/yarn.lock" }}
         paths:
         - ui/node_modules
-  build-go-dev:
-    machine: true
-    shell: /usr/bin/env bash -euo pipefail -c
-    working_directory: /go/src/github.com/hashicorp/vault
-    steps:
-    - run:
-        command: |
-          [ -n "$GO_VERSION" ] || { echo "You must set GO_VERSION"; exit 1; }
-          # Install Go
-          curl -sSLO "https://dl.google.com/go/go${GO_VERSION}.linux-amd64.tar.gz"
-          sudo rm -rf /usr/local/go
-          sudo tar -C /usr/local -xzf "go${GO_VERSION}.linux-amd64.tar.gz"
-          rm -f "go${GO_VERSION}.linux-amd64.tar.gz"
-          GOPATH="/go"
-          mkdir $GOPATH 2>/dev/null || { sudo mkdir $GOPATH && sudo chmod 777 $GOPATH; }
-          echo "export GOPATH='$GOPATH'" >> "$BASH_ENV"
-          echo "export PATH='$PATH:$GOPATH/bin:/usr/local/go/bin'" >> "$BASH_ENV"
-
-          echo "$ go version"
-          go version
-        name: Setup Go
-        working_directory: ~/
-    - checkout
-    - attach_workspace:
-        at: .
-    - run:
-        command: |
-          # Move dev UI assets to expected location
-          rm -rf ./pkg
-          mkdir ./pkg
-
-          # Build dev binary
-          make ci-bootstrap dev
-        name: Build dev binary
-    - persist_to_workspace:
-        paths:
-        - bin
-        root: .
-    environment:
-    - CIRCLECI_CLI_VERSION: 0.1.5546
-    - GO_TAGS: ''
-    - GO_VERSION: 1.13.8
-    - GO111MODULE: 'off'
-    - GOTESTSUM_VERSION: 0.3.3
   test-ui:
     docker:
     - environment:
@@ -158,11 +85,55 @@ jobs:
           export PATH="${PWD}"/bin:${PATH}
           make test-ui-browserstack
         name: Run Browserstack Tests
-  test-go:
+  build-go-dev:
+    machine: true
+    shell: /usr/bin/env bash -euo pipefail -c
+    working_directory: /go/src/github.com/hashicorp/vault
+    steps:
+    - run:
+        command: |
+          [ -n "$GO_VERSION" ] || { echo "You must set GO_VERSION"; exit 1; }
+          # Install Go
+          curl -sSLO "https://dl.google.com/go/go${GO_VERSION}.linux-amd64.tar.gz"
+          sudo rm -rf /usr/local/go
+          sudo tar -C /usr/local -xzf "go${GO_VERSION}.linux-amd64.tar.gz"
+          rm -f "go${GO_VERSION}.linux-amd64.tar.gz"
+          GOPATH="/go"
+          mkdir $GOPATH 2>/dev/null || { sudo mkdir $GOPATH && sudo chmod 777 $GOPATH; }
+          echo "export GOPATH='$GOPATH'" >> "$BASH_ENV"
+          echo "export PATH='$PATH:$GOPATH/bin:/usr/local/go/bin'" >> "$BASH_ENV"
+
+          echo "$ go version"
+          go version
+        name: Setup Go
+        working_directory: ~/
+    - checkout
+    - attach_workspace:
+        at: .
+    - run:
+        command: |
+          # Move dev UI assets to expected location
+          rm -rf ./pkg
+          mkdir ./pkg
+
+          # Build dev binary
+          make ci-bootstrap dev
+        name: Build dev binary
+    - persist_to_workspace:
+        paths:
+        - bin
+        root: .
+    environment:
+    - CIRCLECI_CLI_VERSION: 0.1.5546
+    - GO_TAGS: ''
+    - GO_VERSION: 1.13.8
+    - GO111MODULE: 'off'
+    - GOTESTSUM_VERSION: 0.3.3
+  test-go-remote-docker:
     docker:
     - image: circleci/golang:1.13.10-buster
     working_directory: /go/src/github.com/hashicorp/vault
-    parallelism: 8
+    parallelism: 4
     steps:
     - run:
         command: |
@@ -190,17 +161,26 @@ jobs:
               -C /usr/local/bin \
               "circleci-cli_${CIRCLECI_CLI_VERSION}_linux_amd64/circleci"
 
-          # TODO only run these tests with docker:
-          # go list -test -json  ./...  | jq 'select(.Deps != null) | select(any(.Deps[] ; contains("github.com/hashicorp/vault/helper/testhelpers/docker"))) | .Dir'  |sort -u
+          USE_DOCKER=0
+          USE_DOCKER=1
+
+          if [ $USE_DOCKER == 1 ]; then
+            package_names=$(go list -test -json ./... |
+              jq -r 'select(.Deps != null) |
+                select(any(.Deps[] ; contains("github.com/hashicorp/vault/helper/testhelpers/docker"))) |
+                .ForTest | select(. != null)' |
+                sort -u)
+          else
+            package_names=$(go list -test -json ./... |
+              jq -r 'select(.Deps != null) |
+                select(all(.Deps[] ; contains("github.com/hashicorp/vault/helper/testhelpers/docker")|not)) |
+                .ForTest | select(. != null)' |
+                sort -u)
+          fi
 
           # Split Go tests by prior test times
-          package_names=$(go list \
-              -tags "${GO_TAGS}" \
-              -test ./... \
-            | grep -v /integ \
-            | grep '.test$' | sed 's/.test$//' \
-            | sort \
-            | circleci tests split --split-by=timings --timings-type=classname)
+          package_names=$(echo $package_names |
+            circleci tests split --split-by=timings --timings-type=classname)
 
           # After running tests split step, we are now running the following steps
           # in multiple different containers, each getting a different subset of
@@ -286,17 +266,25 @@ jobs:
               -C /usr/local/bin \
               "circleci-cli_${CIRCLECI_CLI_VERSION}_linux_amd64/circleci"
 
-          # TODO only run these tests with docker:
-          # go list -test -json  ./...  | jq 'select(.Deps != null) | select(any(.Deps[] ; contains("github.com/hashicorp/vault/helper/testhelpers/docker"))) | .Dir'  |sort -u
+          USE_DOCKER=0
+
+          if [ $USE_DOCKER == 1 ]; then
+            package_names=$(go list -test -json ./... |
+              jq -r 'select(.Deps != null) |
+                select(any(.Deps[] ; contains("github.com/hashicorp/vault/helper/testhelpers/docker"))) |
+                .ForTest | select(. != null)' |
+                sort -u)
+          else
+            package_names=$(go list -test -json ./... |
+              jq -r 'select(.Deps != null) |
+                select(all(.Deps[] ; contains("github.com/hashicorp/vault/helper/testhelpers/docker")|not)) |
+                .ForTest | select(. != null)' |
+                sort -u)
+          fi
 
           # Split Go tests by prior test times
-          package_names=$(go list \
-              -tags "${GO_TAGS}" \
-              -test ./... \
-            | grep -v /integ \
-            | grep '.test$' | sed 's/.test$//' \
-            | sort \
-            | circleci tests split --split-by=timings --timings-type=classname)
+          package_names=$(echo $package_names |
+            circleci tests split --split-by=timings --timings-type=classname)
 
           # After running tests split step, we are now running the following steps
           # in multiple different containers, each getting a different subset of
@@ -373,6 +361,136 @@ jobs:
               docker push hashicorp/vault-website
           fi
         name: Build Docker Image if Necessary
+  test-go:
+    docker:
+    - image: circleci/golang:1.13.10-buster
+    working_directory: /go/src/github.com/hashicorp/vault
+    parallelism: 8
+    steps:
+    - run:
+        command: |
+          # If the branch being tested starts with ui/ or docs/ we want to exit the job without failing
+          [[ "$CIRCLE_BRANCH" = ui/* || "$CIRCLE_BRANCH" = docs/* ]] && {
+            # stop the job from this step
+            circleci-agent step halt
+          }
+          # exit with success either way
+          exit 0
+        name: Check branch name
+        working_directory: ~/
+    - checkout
+    - run:
+        command: |
+          set -x
+
+          # Install CircleCI CLI
+          curl -sSL \
+              "https://github.com/CircleCI-Public/circleci-cli/releases/download/v${CIRCLECI_CLI_VERSION}/circleci-cli_${CIRCLECI_CLI_VERSION}_linux_amd64.tar.gz" \
+            | sudo tar --overwrite -xz \
+              -C /usr/local/bin \
+              "circleci-cli_${CIRCLECI_CLI_VERSION}_linux_amd64/circleci"
+
+          USE_DOCKER=0
+
+          if [ $USE_DOCKER == 1 ]; then
+            package_names=$(go list -test -json ./... |
+              jq -r 'select(.Deps != null) |
+                select(any(.Deps[] ; contains("github.com/hashicorp/vault/helper/testhelpers/docker"))) |
+                .ForTest | select(. != null)' |
+                sort -u)
+          else
+            package_names=$(go list -test -json ./... |
+              jq -r 'select(.Deps != null) |
+                select(all(.Deps[] ; contains("github.com/hashicorp/vault/helper/testhelpers/docker")|not)) |
+                .ForTest | select(. != null)' |
+                sort -u)
+          fi
+
+          # Split Go tests by prior test times
+          package_names=$(echo $package_names |
+            circleci tests split --split-by=timings --timings-type=classname)
+
+          # After running tests split step, we are now running the following steps
+          # in multiple different containers, each getting a different subset of
+          # the test packages in their package_names variable.  Each container
+          # has its own remote docker VM.
+
+          # Create a docker network for our testcontainer
+          export TEST_DOCKER_NETWORK_ID=$(docker network list -q -f 'name=vaulttest')
+          if [ -z $TEST_DOCKER_NETWORK_ID ]; then
+            TEST_DOCKER_NETWORK_ID=$(docker network create vaulttest)
+          fi
+
+          # Start a docker testcontainer to run the tests in
+          docker run -d -e TEST_DOCKER_NETWORK_ID \
+            -e DOCKER_CERT_PATH -e DOCKER_HOST -e DOCKER_MACHINE_NAME -e DOCKER_TLS_VERIFY -e NO_PROXY \
+            -e VAULT_TEST_LOG_DIR=/tmp/testlogs \
+            --network vaulttest --name \
+            testcontainer circleci/golang:1.13.10-buster \
+            tail -f /dev/null
+
+          # Run tests
+          make prep
+          mkdir -p test-results/go-test
+          docker exec testcontainer sh -c 'mkdir -p /go/src/github.com/hashicorp/vault'
+          docker cp . testcontainer:/go/src/github.com/hashicorp/vault/
+          docker cp $DOCKER_CERT_PATH/ testcontainer:$DOCKER_CERT_PATH
+
+          docker exec -w /go/src/github.com/hashicorp/vault/ \
+            -e GO111MODULE -e CIRCLECI \
+            testcontainer \
+            gotestsum --format=short-verbose --junitfile test-results/go-test/results.xml -- \
+              -tags "${GO_TAGS}" \
+              -timeout=15m \
+              -parallel=20 \
+               \
+              ${package_names}
+        name: Run Go tests
+        no_output_timeout: 60m
+    - run:
+        command: |
+          docker cp testcontainer:/go/src/github.com/hashicorp/vault/test-results .
+        name: Copy test results
+        when: always
+    - store_artifacts:
+        path: test-results
+    - store_test_results:
+        path: test-results
+    - store_artifacts:
+        path: /tmp/testlogs
+    environment:
+    - CIRCLECI_CLI_VERSION: 0.1.5546
+    - GO_TAGS: ''
+    - GO111MODULE: 'off'
+  pre-flight-checks:
+    docker:
+    - image: circleci/buildpack-deps
+    environment:
+    - CCI_VERSION: 0.1.5691
+    shell: /usr/bin/env bash -euo pipefail
+    steps:
+    - checkout
+    - run:
+        command: |
+          export CCI_PATH=/tmp/circleci-cli/$CCI_VERSION
+          mkdir -p $CCI_PATH
+          NAME=circleci-cli_${CCI_VERSION}_${ARCH}
+          URL=$BASE/v${CCI_VERSION}/${NAME}.tar.gz
+          curl -sSL $URL \
+            | tar --overwrite --strip-components=1 -xz -C $CCI_PATH "${NAME}/circleci"
+          # Add circleci to the path for subsequent steps.
+          echo "export PATH=$CCI_PATH:\$PATH" >> $BASH_ENV
+          # Done, print some debug info.
+          set -x
+          . $BASH_ENV
+          which circleci
+          circleci version
+        environment:
+          ARCH: linux_amd64
+          BASE: https://github.com/CircleCI-Public/circleci-cli/releases/download
+        name: Install CircleCI CLI
+    - run:
+        command: make ci-verify
 workflows:
   ci:
     jobs:
@@ -395,6 +513,9 @@ workflows:
         - install-ui-dependencies
         - build-go-dev
     - test-go:
+        requires:
+        - build-go-dev
+    - test-go-remote-docker:
         requires:
         - build-go-dev
     - test-go-race:
