ci: update Makefile
- Copied from https://github.com/samsalisbury/circleci-multi-file-config/blob/c5c5149583f7733675bb987780a5da5959450f57/copythis.circleci/Makefile

diff --git a/.circleci/Makefile b/.circleci/Makefile
--- a/.circleci/Makefile
+++ b/.circleci/Makefile
@@ -1,36 +1,75 @@
-.PHONY: default
-default: ci-config
+SHELL       := /usr/bin/env bash
+.SHELLFLAGS := -euo pipefail -c
 
-.PHONY: check-circleci-installed
-check-circleci-installed:
-	@command -v circleci > /dev/null 2>&1 || { \
-		echo "Please install circleci-cli, see https://circleci.com/docs/2.0/local-cli/#installation"; \
-		exit 1; }
+# CONFIG is the name of the make target someone
+# would invoke to update the main config file (config.yml).
+CONFIG ?= ci-config
+# VERIFY is the name of the make target someone
+# would invoke to verify the config file.
+VERIFY ?= ci-verify
 
-.PHONY: ci-config
-# ci-config is just an alias for config.yml for now
-ci-config: config.yml
+CCI_INSTALL_LINK := https://circleci.com/docs/2.0/local-cli/\#installation
+CCI_INSTALL_MSG := Please install CircleCI CLI. See $(CCI_INSTALL_LINK)
+CCI_VERSION := $(shell circleci version 2> /dev/null)
+ifneq ($(CCI_VERSION),)
+CIRCLECI := circleci
+else
+# Attempting to use the CLI fails with installation instructions.
+CIRCLECI := echo '$(CCI_INSTALL_MSG)'; exit 1; \#
+endif
 
-CONFIG_SOURCE_DIR := config/
-CONFIG_SOURCE     := $(shell find config/) Makefile
-OUT               := config.yml
-TMP               := .tmp/config.yml.tmp
-CONFIG_21         := .tmp/config.2.1.tmp
+SOURCE_DIR     := config
+SOURCE_YML     := $(shell [ ! -d $(SOURCE_DIR) ] || find $(SOURCE_DIR) -name '*.yml')
+CONFIG_SOURCE  := Makefile $(SOURCE_YML) | $(SOURCE_DIR)
+OUT            := config.yml
+TMP            := .tmp/config-processed
+CONFIG_PACKED  := .tmp/config-packed
 
-# Ensure the .tmp dir exists.
+default: help
+
+help:
+	@echo "Usage:"
+	@echo "  make $(CONFIG): recompile config.yml from $(SOURCE_DIR)/"
+	@echo "  make $(VERIFY): verify that config.yml is a true mapping from $(SOURCE_DIR)/"
+	@echo
+	@echo "Diagnostics:"
+	@[ -z "$(CCI_VERSION)" ] || echo "  circleci-cli version $(CCI_VERSION)"
+	@[ -n "$(CCI_VERSION)" ] || echo "  $(CCI_INSTALL_MSG)"
+
+$(SOURCE_DIR):
+	@echo No source directory $(SOURCE_DIR) found. Try make init.; exit 1
+
+# Make sure our .tmp dir exists.
 $(shell [ -d .tmp ] || mkdir .tmp)
 
+.PHONY: $(CONFIG)
+$(CONFIG): $(OUT)
+
+.PHONY: $(VERIFY)
+$(VERIFY): config-up-to-date
+	@$(CIRCLECI) config validate $(OUT)
+
+CONFIG_ROOT := $(SOURCE_DIR)/@$(SOURCE_DIR).yml
+
+.PHONY: init
+init: ## init creates just enough to allow make ci-config to run without error.
+	@[ ! -d $(SOURCE_DIR) ] || { echo "Source directory $(SOURCE_DIR)/ already exists."; exit 1; }
+	@mkdir -p $(SOURCE_DIR) $(SOURCE_DIR)/{jobs,commands,workflows}
+	@printf -- "---\nversion: 2.1\njobs:\n" > $(CONFIG_ROOT)
+	@echo File $(CONFIG_ROOT) created.
+
+GENERATED_FILE_HEADER := \#\#\# Generated by 'make $(CONFIG)' do not manually edit this file. 
 define GEN_CONFIG
-	@circleci config pack $(CONFIG_SOURCE_DIR) > $(CONFIG_21)
-	@echo "### Generated by 'make ci-config' do not manually edit this file." > $@
-	@circleci config process $(CONFIG_21) >> $@
+	@$(CIRCLECI) config pack $(SOURCE_DIR) > $(CONFIG_PACKED)
+	@echo "$(GENERATED_FILE_HEADER)" > $@
+	@$(CIRCLECI) config process $(CONFIG_PACKED) >> $@
 endef
 
-$(OUT): $(CONFIG_SOURCE) check-circleci-installed
+$(OUT): $(CONFIG_SOURCE) 
 	$(GEN_CONFIG)
 	@echo "$@ updated"
 
-$(TMP): $(CONFIG_SOURCE) check-circleci-installed
+$(TMP): $(CONFIG_SOURCE) 
 	$(GEN_CONFIG)
 
 .PHONY: config-up-to-date
@@ -38,10 +77,6 @@ config-up-to-date: $(TMP) # Note this must not depend on $(OUT)!
 	@if diff config.yml $<; then \
 		echo "Generated $(OUT) is up to date!"; \
 	else \
-		echo "Generated $(OUT) is out of date, run make ci-config to update."; \
+		echo "Generated $(OUT) is out of date, run make $(CONFIG) to update."; \
 		exit 1; \
 	fi
-
-.PHONY: ci-verify
-ci-verify: config-up-to-date
-	@circleci config validate config.yml
