Should use "change" not "changes" (#13020)

diff --git a/.github/workflows/changelog-checker.yml b/.github/workflows/changelog-checker.yml
--- a/.github/workflows/changelog-checker.yml
+++ b/.github/workflows/changelog-checker.yml
@@ -37,6 +37,9 @@ jobs:
             # "Enhancement is not a valid type of changelog entry, but it's a common mistake.
             echo "Found invalid type (enhancement) in changelog - did you mean improvement?"
             exit 1
+          elif grep -q ':changes$' $changelog_files; then
+            echo "Found invalid type (changes) in changelog - did you mean change?"
+            exit 1
           elif grep -q ':bugs$' $changelog_files; then
             echo "Found invalid type (bugs) in changelog - did you mean bug?"
             exit 1
