Use a public channel. Sabotage all test suites to fail.

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -106,19 +106,22 @@ jobs:
     if: |
       needs.verify-changes.outputs.is_docs_change == 'false' &&
       needs.verify-changes.outputs.is_ui_change == 'false'
-    uses: ./.github/workflows/test-go.yml
-    with:
-      # The regular Go tests use an extra runner to execute the
-      # binary-dependent tests. We isolate them there so that the
-      # other tests aren't slowed down waiting for a binary build.
-      binary-tests: true
-      total-runners: 16
-      go-arch: amd64
-      go-tags: '${{ needs.setup.outputs.go-tags }},deadlock'
-      runs-on: ${{ needs.setup.outputs.compute-large }}
-      enterprise: ${{ needs.setup.outputs.enterprise }}
-      test-timing-cache-key: go-test-timing-standard
-    secrets: inherit
+    runs-on: ${{ fromJSON(needs.setup.outputs.compute-small) }}
+    steps:
+      - run: false
+#    uses: ./.github/workflows/test-go.yml
+#    with:
+#      # The regular Go tests use an extra runner to execute the
+#      # binary-dependent tests. We isolate them there so that the
+#      # other tests aren't slowed down waiting for a binary build.
+#      binary-tests: true
+#      total-runners: 16
+#      go-arch: amd64
+#      go-tags: '${{ needs.setup.outputs.go-tags }},deadlock'
+#      runs-on: ${{ needs.setup.outputs.compute-large }}
+#      enterprise: ${{ needs.setup.outputs.enterprise }}
+#      test-timing-cache-key: go-test-timing-standard
+#    secrets: inherit
 
   test-go-testonly:
     name: Run Go tests tagged with testonly
@@ -129,16 +132,19 @@ jobs:
     if: |
       needs.verify-changes.outputs.is_docs_change == 'false' &&
       needs.verify-changes.outputs.is_ui_change == 'false'
-    uses: ./.github/workflows/test-go.yml
-    with:
-      testonly: true
-      total-runners: 2 # test runners cannot be less than 2
-      go-arch: amd64
-      go-tags: '${{ needs.setup.outputs.go-tags }},deadlock,testonly'
-      runs-on: ${{ needs.setup.outputs.compute-large }}
-      enterprise: ${{ needs.setup.outputs.enterprise }}
-      test-timing-cache-enabled: false
-    secrets: inherit
+    runs-on: ${{ fromJSON(needs.setup.outputs.compute-small) }}
+    steps:
+      - run: false
+#    uses: ./.github/workflows/test-go.yml
+#    with:
+#      testonly: true
+#      total-runners: 2 # test runners cannot be less than 2
+#      go-arch: amd64
+#      go-tags: '${{ needs.setup.outputs.go-tags }},deadlock,testonly'
+#      runs-on: ${{ needs.setup.outputs.compute-large }}
+#      enterprise: ${{ needs.setup.outputs.enterprise }}
+#      test-timing-cache-enabled: false
+#    secrets: inherit
 
   test-go-race:
     name: Run Go tests with data race detection
@@ -150,21 +156,24 @@ jobs:
       github.event.pull_request.draft == false &&
       needs.verify-changes.outputs.is_docs_change == 'false' &&
       needs.verify-changes.outputs.is_ui_change == 'false'
-    uses: ./.github/workflows/test-go.yml
-    with:
-      total-runners: 16
-      env-vars: |
-        {
-          "VAULT_CI_GO_TEST_RACE": 1
-        }
-      extra-flags: '-race'
-      go-arch: amd64
-      go-tags: ${{ needs.setup.outputs.go-tags }}
-      runs-on: ${{ needs.setup.outputs.compute-large }}
-      enterprise: ${{ needs.setup.outputs.enterprise }}
-      name: "race"
-      test-timing-cache-key: go-test-timing-race
-    secrets: inherit
+    runs-on: ${{ fromJSON(needs.setup.outputs.compute-small) }}
+    steps:
+      - run: false
+#    uses: ./.github/workflows/test-go.yml
+#    with:
+#      total-runners: 16
+#      env-vars: |
+#        {
+#          "VAULT_CI_GO_TEST_RACE": 1
+#        }
+#      extra-flags: '-race'
+#      go-arch: amd64
+#      go-tags: ${{ needs.setup.outputs.go-tags }}
+#      runs-on: ${{ needs.setup.outputs.compute-large }}
+#      enterprise: ${{ needs.setup.outputs.enterprise }}
+#      name: "race"
+#      test-timing-cache-key: go-test-timing-race
+#    secrets: inherit
 
   test-go-fips:
     name: Run Go tests with FIPS configuration
@@ -207,88 +216,91 @@ jobs:
       contains(github.event.pull_request.labels.*.name, 'ui')
     needs:
       - setup
-    permissions:
-      id-token: write
-      contents: read
-    runs-on: ${{ fromJSON(needs.setup.outputs.compute-largem) }}
+    runs-on: ${{ fromJSON(needs.setup.outputs.compute-small) }}
     steps:
-      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
-      - uses: ./.github/actions/set-up-go
-        with:
-          github-token: ${{ secrets.ELEVATED_GITHUB_TOKEN }}
-      # Setup node.js without caching to allow running npm install -g yarn (next step)
-      - uses: actions/setup-node@e33196f7422957bea03ed53f6fbb155025ffc7b8 # v3.7.0
-        with:
-          node-version-file: './ui/package.json'
-      - id: install-yarn
-        run: |
-          npm install -g yarn
-      # Setup node.js with caching using the yarn.lock file
-      - uses: actions/setup-node@e33196f7422957bea03ed53f6fbb155025ffc7b8 # v3.7.0
-        with:
-          node-version-file: './ui/package.json'
-          cache: yarn
-          cache-dependency-path: ui/yarn.lock
-      - id: install-browser
-        uses: browser-actions/setup-chrome@c485fa3bab6be59dce18dbc18ef6ab7cbc8ff5f1 # v1.2.0
-      - id: ui-dependencies
-        name: ui-dependencies
-        working-directory: ./ui
-        run: |
-          yarn install --frozen-lockfile
-          npm rebuild node-sass
-      - id: vault-auth
-        name: Authenticate to Vault
-        if: github.repository == 'hashicorp/vault-enterprise'
-        run: vault-auth
-      - id: secrets
-        name: Fetch secrets
-        if: github.repository == 'hashicorp/vault-enterprise'
-        uses: hashicorp/vault-action@130d1f5f4fe645bb6c83e4225c04d64cfb62de6e
-        with:
-          url: ${{ steps.vault-auth.outputs.addr }}
-          caCertificate: ${{ steps.vault-auth.outputs.ca_certificate }}
-          token: ${{ steps.vault-auth.outputs.token }}
-          secrets: |
-            kv/data/github/hashicorp/vault-enterprise/github-token token | PRIVATE_REPO_GITHUB_TOKEN;
-            kv/data/github/hashicorp/vault-enterprise/license license_1 | VAULT_LICENSE;
-      - id: setup-git
-        name: Setup Git
-        if: github.repository == 'hashicorp/vault-enterprise'
-        run: |
-          git config --global url."https://${{ steps.secrets.outputs.PRIVATE_REPO_GITHUB_TOKEN }}@github.com".insteadOf https://github.com
-      - id: build-go-dev
-        name: build-go-dev
-        run: |
-          rm -rf ./pkg
-          mkdir ./pkg
-
-          make ci-bootstrap dev
-      - id: test-ui
-        name: test-ui
-        env:
-          VAULT_LICENSE: ${{ steps.secrets.outputs.VAULT_LICENSE }}
-        run: |
-          export PATH="${PWD}/bin:${PATH}"
-
-          if [ "${{ github.repository }}" == 'hashicorp/vault' ] ; then
-            export VAULT_LICENSE="${{ secrets.VAULT_LICENSE }}"
-          fi
-
-          # Run Ember tests
-          cd ui
-          mkdir -p test-results/qunit
-          yarn test:oss
-      - uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # v3.1.2
-        with:
-          name: test-results-ui
-          path: ui/test-results
-        if: success() || failure()
-      - uses: test-summary/action@62bc5c68de2a6a0d02039763b8c754569df99e3f # v2.1
-        with:
-          paths: "ui/test-results/qunit/results.xml"
-          show: "fail"
-        if: always()
+      - run: false
+#    permissions:
+#      id-token: write
+#      contents: read
+#    runs-on: ${{ fromJSON(needs.setup.outputs.compute-largem) }}
+#    steps:
+#      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
+#      - uses: ./.github/actions/set-up-go
+#        with:
+#          github-token: ${{ secrets.ELEVATED_GITHUB_TOKEN }}
+#      # Setup node.js without caching to allow running npm install -g yarn (next step)
+#      - uses: actions/setup-node@e33196f7422957bea03ed53f6fbb155025ffc7b8 # v3.7.0
+#        with:
+#          node-version-file: './ui/package.json'
+#      - id: install-yarn
+#        run: |
+#          npm install -g yarn
+#      # Setup node.js with caching using the yarn.lock file
+#      - uses: actions/setup-node@e33196f7422957bea03ed53f6fbb155025ffc7b8 # v3.7.0
+#        with:
+#          node-version-file: './ui/package.json'
+#          cache: yarn
+#          cache-dependency-path: ui/yarn.lock
+#      - id: install-browser
+#        uses: browser-actions/setup-chrome@c485fa3bab6be59dce18dbc18ef6ab7cbc8ff5f1 # v1.2.0
+#      - id: ui-dependencies
+#        name: ui-dependencies
+#        working-directory: ./ui
+#        run: |
+#          yarn install --frozen-lockfile
+#          npm rebuild node-sass
+#      - id: vault-auth
+#        name: Authenticate to Vault
+#        if: github.repository == 'hashicorp/vault-enterprise'
+#        run: vault-auth
+#      - id: secrets
+#        name: Fetch secrets
+#        if: github.repository == 'hashicorp/vault-enterprise'
+#        uses: hashicorp/vault-action@130d1f5f4fe645bb6c83e4225c04d64cfb62de6e
+#        with:
+#          url: ${{ steps.vault-auth.outputs.addr }}
+#          caCertificate: ${{ steps.vault-auth.outputs.ca_certificate }}
+#          token: ${{ steps.vault-auth.outputs.token }}
+#          secrets: |
+#            kv/data/github/hashicorp/vault-enterprise/github-token token | PRIVATE_REPO_GITHUB_TOKEN;
+#            kv/data/github/hashicorp/vault-enterprise/license license_1 | VAULT_LICENSE;
+#      - id: setup-git
+#        name: Setup Git
+#        if: github.repository == 'hashicorp/vault-enterprise'
+#        run: |
+#          git config --global url."https://${{ steps.secrets.outputs.PRIVATE_REPO_GITHUB_TOKEN }}@github.com".insteadOf https://github.com
+#      - id: build-go-dev
+#        name: build-go-dev
+#        run: |
+#          rm -rf ./pkg
+#          mkdir ./pkg
+#
+#          make ci-bootstrap dev
+#      - id: test-ui
+#        name: test-ui
+#        env:
+#          VAULT_LICENSE: ${{ steps.secrets.outputs.VAULT_LICENSE }}
+#        run: |
+#          export PATH="${PWD}/bin:${PATH}"
+#
+#          if [ "${{ github.repository }}" == 'hashicorp/vault' ] ; then
+#            export VAULT_LICENSE="${{ secrets.VAULT_LICENSE }}"
+#          fi
+#
+#          # Run Ember tests
+#          cd ui
+#          mkdir -p test-results/qunit
+#          yarn test:oss
+#      - uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # v3.1.2
+#        with:
+#          name: test-results-ui
+#          path: ui/test-results
+#        if: success() || failure()
+#      - uses: test-summary/action@62bc5c68de2a6a0d02039763b8c754569df99e3f # v2.1
+#        with:
+#          paths: "ui/test-results/qunit/results.xml"
+#          show: "fail"
+#        if: always()
 
   tests-completed:
     needs:
@@ -328,7 +340,7 @@ jobs:
         env:
           SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
         with:
-          channel-id: "DE0MRNZSQ" # "C05AABYEA9Y" # sent to #feed-vault-ci-official
+          channel-id: "C05Q4D5V89W" # "C05AABYEA9Y" # sent to #feed-vault-ci-official
           payload: |
             {
               "text": "OSS test failures on ${{ github.ref_name }}",
