spacing

diff --git a/.github/workflows/drepecated-functions-checker.yml b/.github/workflows/drepecated-functions-checker.yml
--- a/.github/workflows/drepecated-functions-checker.yml
+++ b/.github/workflows/drepecated-functions-checker.yml
@@ -16,48 +16,48 @@ jobs:
           cache: true
       - name: staticcheck
         run: |
-echo "Installing staticcheck"
-go install honnef.co/go/tools/cmd/staticcheck@latest
+          echo "Installing staticcheck"
+          go install honnef.co/go/tools/cmd/staticcheck@latest
 
 
-echo "Running staticcheck to look for deprecations"
+          echo "Running staticcheck to look for deprecations"
 
-# use entire package name for packages
-ignoreList=("github.com/golang/protobuf/proto"
-"errwrap.Wrapf"
-"io/ioutil"
-"ptypes"
-".RawRequestWithContext"
-".RawRequest"
-"cloud.google.com/go/monitoring/apiv3"
-"crypto/dsa"
-"x509.ParseCRL"
-"ACL().Create"
-"ACL().Destroy" 
-"Statements.CreationStatements"
-"Statements.RevocationStatements"
-"Statements.RollbackStatements"
-"strings.Title"
-"connState.NegotiatedProtocolIsMutual")
+          # use entire package name for packages
+          ignoreList=("github.com/golang/protobuf/proto"
+          "errwrap.Wrapf"
+          "io/ioutil"
+          "ptypes"
+          ".RawRequestWithContext"
+          ".RawRequest"
+          "cloud.google.com/go/monitoring/apiv3"
+          "crypto/dsa"
+          "x509.ParseCRL"
+          "ACL().Create"
+          "ACL().Destroy" 
+          "Statements.CreationStatements"
+          "Statements.RevocationStatements"
+          "Statements.RollbackStatements"
+          "strings.Title"
+          "connState.NegotiatedProtocolIsMutual")
 
-# run staticcheck
-staticcheck ./... | grep deprecated > staticcheckOutput.txt  
+          # run staticcheck
+          staticcheck ./... | grep deprecated > staticcheckOutput.txt  
 
-# delete ignored values from the output
-for val in ${ignoreList[@]}; do
-  grep -v $val staticcheckOutput.txt > tmpfile && mv tmpfile staticcheckOutput.txt
-  rm -rf tmpfile
-done
+          # delete ignored values from the output
+          for val in ${ignoreList[@]}; do
+            grep -v $val staticcheckOutput.txt > tmpfile && mv tmpfile staticcheckOutput.txt
+            rm -rf tmpfile
+          done
 
 
-if [ -s staticcheckOutput.txt ]
-then
-     echo "Use of deprecated function, variable, constant or field found"
-     cat staticcheckOutput.txt 
-     # output file clean up 
-     rm -rf staticcheckOutput.txt  
-     exit 1 
-else
-     echo "Use of deprecated function, variable, constant or field not found"
-     rm -rf staticcheckOutput.txt  
-fi
+          if [ -s staticcheckOutput.txt ]
+          then
+              echo "Use of deprecated function, variable, constant or field found"
+              cat staticcheckOutput.txt 
+              # output file clean up 
+              rm -rf staticcheckOutput.txt  
+              exit 1 
+          else
+              echo "Use of deprecated function, variable, constant or field not found"
+              rm -rf staticcheckOutput.txt  
+          fi
