Add temp fake failure step

diff --git a/.github/workflows/test-run-enos-scenario-matrix.yml b/.github/workflows/test-run-enos-scenario-matrix.yml
--- a/.github/workflows/test-run-enos-scenario-matrix.yml
+++ b/.github/workflows/test-run-enos-scenario-matrix.yml
@@ -168,15 +168,20 @@ jobs:
           rm -rf /tmp/enos*
           rm -rf ./enos/support
           rm -rf ./enos/.enos
+      # Create temporary failure to test failure condition
+      - name: Fake failure step
+        id: fake_failure
+        run: |
+          echo "This run failed!" 1>&2
+          exit 1
       # Send Slack notification to #feed-vault-enos-failures for any failures in the above `run` job.
       # There is an incoming webhook set up on the "Enos Vault Failure Bot" Slackbot https://api.slack.com/apps/A05E31CH1LG/incoming-webhooks
       - name: Send Slack notification on Enos failure
         uses: hashicorp/actions-slack-status@v1
-        # Temporary "success" condition for testing on PR; revert to "failure" before merge to main
-        if: ${{ steps.run.outcome == 'success' || steps.run_retry.outcome == 'success' }}
+        # if: ${{ steps.run.outcome == 'failure' || steps.run_retry.outcome == 'failure' }}
+        # Temporary "failure" test; revert to above statement before merge to main
+        if: ${{ steps.fake_failure.outcome == 'failure' }}
         with:
-          # Temporary "success" message; remove before merge to main
-          success-message: "An Enos scenario run succeeded. \nRepo: `${{ github.repository }}`"
           failure-message: "An Enos scenario run failed. \nRepo: `${{ github.repository }}`"
           status: ${{job.status}}
           slack-webhook-url: ${{secrets.SLACK_WEBHOOK_URL}}
