sync actions with main
Signed-off-by: Ryan Cragun <me@ryan.ec>

diff --git a/.github/workflows/test-go.yml b/.github/workflows/test-go.yml
--- a/.github/workflows/test-go.yml
+++ b/.github/workflows/test-go.yml
@@ -60,6 +60,16 @@ on:
         required: false
         default: false
         type: boolean
+      test-timing-cache-enabled:
+        description: Cache the gotestsum test timing data.
+        required: false
+        default: true
+        type: boolean
+      test-timing-cache-key:
+        description: The cache key to use for gotestsum test timing data.
+        required: false
+        default: go-test-reports
+        type: string
       checkout-ref:
         description: The ref to use for checkout.
         required: false
@@ -68,10 +78,10 @@ on:
     outputs:
       data-race-output:
         description: A textual output of any data race detector failures
-        value: ${{ jobs.test-go.outputs.data-race-output }}
+        value: ${{ jobs.status.outputs.data-race-output }}
       data-race-result:
         description: Whether or not there were any data races detected
-        value: ${{ jobs.test-go.outputs.data-race-result }}
+        value: ${{ jobs.status.outputs.data-race-result }}
 
 env: ${{ fromJSON(inputs.env-vars) }}
 
@@ -86,7 +96,7 @@ jobs:
       matrix: ${{ steps.build.outputs.matrix }}
       matrix_ids: ${{ steps.build.outputs.matrix_ids }}
     steps:
-      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
+      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
         with:
           ref: ${{ inputs.checkout-ref }}
       - uses: ./.github/actions/set-up-go
@@ -102,7 +112,7 @@ jobs:
       - name: Fetch Secrets
         id: secrets
         if: github.repository == 'hashicorp/vault-enterprise'
-        uses: hashicorp/vault-action@affa6f04da5c2d55e6e115b7d1b044a6b1af8c74
+        uses: hashicorp/vault-action@9f522b85981b491eab9a52c144d15aedbd0bf371 # v2.8.0
         with:
           url: ${{ steps.vault-auth.outputs.addr }}
           caCertificate: ${{ steps.vault-auth.outputs.ca_certificate }}
@@ -112,11 +122,6 @@ jobs:
             kv/data/github/${{ github.repository }}/github-token username-and-token | github-token;
             kv/data/github/${{ github.repository }}/license license_1 | VAULT_LICENSE_CI;
             kv/data/github/${{ github.repository }}/license license_2 | VAULT_LICENSE_2;
-            kv/data/github/${{ github.repository }}/hcp-link HCP_API_ADDRESS;
-            kv/data/github/${{ github.repository }}/hcp-link HCP_AUTH_URL;
-            kv/data/github/${{ github.repository }}/hcp-link HCP_CLIENT_ID;
-            kv/data/github/${{ github.repository }}/hcp-link HCP_CLIENT_SECRET;
-            kv/data/github/${{ github.repository }}/hcp-link HCP_RESOURCE_ID;
       - id: setup-git-private
         name: Setup Git configuration (private)
         if: github.repository == 'hashicorp/vault-enterprise'
@@ -167,7 +172,7 @@ jobs:
           # testonly tagged tests need an additional tag to be included
           # also running some extra tests for sanity checking with the testonly build tag
           (
-            go list -tags=testonly ./vault/external_tests/{kv,token,*replication-perf*,*testonly*} ./vault/ | gotestsum tool ci-matrix --debug \
+            go list -tags=testonly ./vault/external_tests/{kv,token,*replication-perf*,*testonly*} ./command/*testonly* ./vault/ | gotestsum tool ci-matrix --debug \
               --partitions "${{ inputs.total-runners }}" \
               --timing-files '${{ steps.metadata.outputs.go-test-dir }}/*.json' > matrix.json
           )
@@ -223,11 +228,10 @@ jobs:
       GOPRIVATE: github.com/hashicorp/*
       TIMEOUT_IN_MINUTES: ${{ inputs.timeout-minutes }}
     outputs:
-      data-race-result : ${{ steps.data-race-check.outputs.data-race-result }}
-      data-race-output : ${{ steps.data-race-check.outputs.data-race-output }}
       go-test-results-download-pattern: ${{ steps.metadata.outputs.go-test-results-download-pattern }}
+      data-race-log-download-pattern: ${{ steps.metadata.outputs.data-race-log-download-pattern }}
     steps:
-      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
+      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
         with:
           ref: ${{ inputs.checkout-ref }}
       - uses: ./.github/actions/set-up-go
@@ -255,9 +259,15 @@ jobs:
           gotestsum_jsonfile=${go_test_dir}/${gotestsum_results_prefix}-${name}.json    # test-results/go-test/results-1-testonly.json
           gotestsum_timing_events=failure-summary-${name}.json                          # failure-summary-1-testonly.json
           failure_summary_file_name="failure-summary-${name}.md"                        # failure-summary-1-testonly.md
+          data_race_log_file="data-race.log"                                            # data-race.log
+          data_race_log_download_pattern="data-race-*.log"                              # data-race-*.log
+          data_race_log_upload_key="data-race-${name}.log"                              # data-race-1-testonly.log
           {
             echo "name=${name}"
             echo "failure-summary-file-name=${failure_summary_file_name}"
+            echo "data-race-log-file=${data_race_log_file}"
+            echo "data-race-log-download-pattern=${data_race_log_download_pattern}"
+            echo "data-race-log-upload-key=${data_race_log_upload_key}"
             echo "go-test-dir=${go_test_dir}"
             echo "go-test-log-archive-name=${go_test_log_archive_name}"
             echo "go-test-log-dir=${go_test_log_dir}"
@@ -276,7 +286,7 @@ jobs:
       - name: Fetch Secrets
         id: secrets
         if: github.repository == 'hashicorp/vault-enterprise'
-        uses: hashicorp/vault-action@affa6f04da5c2d55e6e115b7d1b044a6b1af8c74
+        uses: hashicorp/vault-action@9f522b85981b491eab9a52c144d15aedbd0bf371 # v2.8.0
         with:
           url: ${{ steps.vault-auth.outputs.addr }}
           caCertificate: ${{ steps.vault-auth.outputs.ca_certificate }}
@@ -286,11 +296,6 @@ jobs:
             kv/data/github/${{ github.repository }}/github-token username-and-token | github-token;
             kv/data/github/${{ github.repository }}/license license_1 | VAULT_LICENSE_CI;
             kv/data/github/${{ github.repository }}/license license_2 | VAULT_LICENSE_2;
-            kv/data/github/${{ github.repository }}/hcp-link HCP_API_ADDRESS;
-            kv/data/github/${{ github.repository }}/hcp-link HCP_AUTH_URL;
-            kv/data/github/${{ github.repository }}/hcp-link HCP_CLIENT_ID;
-            kv/data/github/${{ github.repository }}/hcp-link HCP_CLIENT_SECRET;
-            kv/data/github/${{ github.repository }}/hcp-link HCP_RESOURCE_ID;
       - id: setup-git-private
         name: Setup Git configuration (private)
         if: github.repository == 'hashicorp/vault-enterprise'
@@ -301,8 +306,10 @@ jobs:
         if: github.repository != 'hashicorp/vault-enterprise'
         run: |
           git config --global url."https://${{ secrets.ELEVATED_GITHUB_TOKEN}}@github.com".insteadOf https://github.com
-      - id: build
-        if: inputs.binary-tests && matrix.id == inputs.total-runners
+      - uses: ./.github/actions/install-external-tools
+      - if: inputs.binary-tests && matrix.id == inputs.total-runners
+        name: Build dev binary for binary tests
+        # The dev mode binary has to exist for binary tests that are dispatched on the last runner.
         env:
           GOPRIVATE: github.com/hashicorp/*
         run: time make prep dev
@@ -388,33 +395,35 @@ jobs:
           if [[ ${{ github.repository }} == 'hashicorp/vault' ]]; then
             export VAULT_LICENSE_CI=${{ secrets.ci_license }}
             export VAULT_LICENSE_2=${{ secrets.ci_license_2 }}
-            export HCP_API_ADDRESS=${{ secrets.HCP_API_ADDRESS }}
-            export HCP_AUTH_URL=${{ secrets.HCP_AUTH_URL }}
-            export HCP_CLIENT_ID=${{ secrets.HCP_CLIENT_ID }}
-            export HCP_CLIENT_SECRET=${{ secrets.HCP_CLIENT_SECRET }}
-            export HCP_RESOURCE_ID=${{ secrets.HCP_RESOURCE_ID }}
-            # Temporarily removing this variable to cause HCP Link tests
-            # to be skipped.
-            #export HCP_SCADA_ADDRESS=${{ secrets.HCP_SCADA_ADDRESS }}
           fi
+
+          # The docker/binary tests are more expensive, and we've had problems with timeouts when running at full
+          # parallelism.  The default if -p isn't specified is to use NumCPUs, which seems fine for regular tests.
+          package_parallelism=""
 
           if [ -f bin/vault ]; then
             VAULT_BINARY="$(pwd)/bin/vault"
             export VAULT_BINARY
+
+            package_parallelism="-p 2"
           fi
 
           # On a release branch, add a flag to rerun failed tests
           # shellcheck disable=SC2193 # can get false positive for this comparision
           if [[  "${{ github.base_ref }}" == release/* ]] || [[  -z "${{ github.base_ref }}" && "${{ github.ref_name }}" == release/* ]]
           then
-           RERUN_FAILS="--rerun-fails"
+            # TODO remove this extra condition once 1.15 is about to released GA
+            if [[  "${{ github.base_ref }}" != release/1.15* ]] || [[  -z "${{ github.base_ref }}" && "${{ github.ref_name }}" != release/1.15* ]]
+            then
+              RERUN_FAILS="--rerun-fails"
+            fi
           fi
 
           VAULT_TEST_LOG_DIR='${{ steps.metadata.outputs.go-test-log-dir-absolute }}'
           export VAULT_TEST_LOG_DIR
           mkdir -p "$VAULT_TEST_LOG_DIR"
           # shellcheck disable=SC2086 # can't quote RERUN_FAILS
-          GOARCH=${{ inputs.go-arch }} \
+          GOARCH=${{ inputs.go-arch }} VAULT_ADDR='' \
             gotestsum --format=short-verbose \
               --junitfile '${{ steps.metadata.outputs.gotestsum-junitfile }}' \
               --jsonfile '${{ steps.metadata.outputs.gotestsum-jsonfile }}' \
@@ -422,15 +431,26 @@ jobs:
               $RERUN_FAILS \
               --packages "$packages" \
               -- \
+              $package_parallelism \
               -tags "${{ inputs.go-tags }}" \
               -timeout=${{ env.TIMEOUT_IN_MINUTES }}m \
               -parallel=${{ inputs.go-test-parallelism }} \
               ${{ inputs.extra-flags }} \
       - name: Prepare datadog-ci
-        if: github.repository == 'hashicorp/vault' && (success() || failure())
+        if: (github.repository == 'hashicorp/vault' || github.repository == 'hashicorp/vault-enterprise') && (success() || failure())
         continue-on-error: true
         run: |
-          curl -L --fail "https://github.com/DataDog/datadog-ci/releases/latest/download/datadog-ci_linux-x64" --output "/usr/local/bin/datadog-ci"
+          if type datadog-ci > /dev/null 2>&1; then
+            exit 0
+          fi
+          # Curl does not always exit 1 if things go wrong. To determine if this is successful we'll
+          # we'll silence all non-error output and check the results to determine success.
+          if ! out="$(curl -sSL --fail https://github.com/DataDog/datadog-ci/releases/latest/download/datadog-ci_linux-x64 --output /usr/local/bin/datadog-ci 2>&1)"; then
+            printf "failed to download datadog-ci: %s" "$out"
+          fi
+          if [[ -n "$out" ]]; then
+            printf "failed to download datadog-ci: %s" "$out"
+          fi
           chmod +x /usr/local/bin/datadog-ci
       - name: Upload test results to DataDog
         continue-on-error: true
@@ -473,14 +493,18 @@ jobs:
         run: |
           # Scan gotestsum output files for data race errors.
           data_race_tests=()
+          data_race_log='${{ steps.metadata.outputs.data-race-log-file }}'
           for file in *.json; do
             # Check if test results contains offending phrase
             if grep -q "WARNING: DATA RACE" "$file"; then
               data_race_tests+=("test-go (${{ matrix.id }})")
+              touch "$data_race_log"
 
-              # Print failing matrix tests
-              echo "=============== test-go (${{ matrix.id }}) ==========================="
-              sed -n '/WARNING: DATA RACE/,/==================/p' "$file" | jq -r -j '.Output'
+              # Write output to our log file so we can aggregate it in the final workflow
+              {
+                echo "=============== test-go (${{ matrix.id }}) ==========================="
+                sed -n '/WARNING: DATA RACE/,/==================/p' "$file" | jq -r -j '.Output'
+              } | tee -a "$data_race_log"
             fi
           done
 
@@ -489,11 +513,17 @@ jobs:
           if (("${#data_race_tests[@]}" > 0)); then
             result="failure"
           fi
-
-          {
-            echo "data-race-result=${result}"
-            echo -n "data-race-output=${data_race_tests[*]}"
-          } | tee -a "$GITHUB_OUTPUT"
+          echo "data-race-result=${result}" | tee -a "$GITHUB_OUTPUT"
+      - name: Upload data race detector failure log
+        if: steps.data-race-check.outputs.data-race-result == 'failure'
+        uses: actions/upload-artifact@26f96dfa697d77e81fd5907df203aa23a56210a8 # v4.3.0
+        with:
+          name: ${{ steps.metadata.outputs.data-race-log-upload-key }}
+          path: ${{ steps.metadata.outputs.go-test-dir }}/${{ steps.metadata.outputs.data-race-log-file }}
+          # Set the minimum retention possible. We only upload this because it's the only way to
+          # aggregate results from matrix workflows.
+          retention-days: 1
+          if-no-files-found: error # Make sure we always upload the data race logs if it failed
       # GitHub Actions doesn't expose the job ID or the URL to the job execution,
       # so we have to fetch it from the API
       - name: Fetch job logs URL
@@ -550,7 +580,7 @@ jobs:
         continue-on-error: true
         run: |
           # This jq query filters out successful tests, leaving only the failures.
-          # Then, it formats the results into rows of a Markdown table.
+          # Then, it formats the results into rows of a Markdown table.k
           # An example row will resemble this:
           # | github.com/hashicorp/vault/package | TestName | fips | 0 | 2 | [view results](github.com/link-to-logs) |
           jq -r -n 'inputs
@@ -573,27 +603,48 @@ jobs:
       - test-matrix
       - test-go
     runs-on: ${{ fromJSON(inputs.runs-on-small) }}
+    outputs:
+      data-race-output: ${{ steps.status.outputs.data-race-output }}
+      data-race-result: ${{ steps.status.outputs.data-race-result }}
     steps:
+      - uses: actions/download-artifact@6b208ae046db98c579e8a3aa621ab581ff575935 # v4.1.1
+        with:
+          pattern: ${{ needs.test-go.outputs.data-race-log-download-pattern }}
+          path: data-race-logs
+          merge-multiple: true
       # Determine our success/failure status by checking the result status and data race status.
       - id: status
         name: Determine status result
         run: |
           # Determine status result
           result="success"
+
+          # Aggregate all of our test workflows and determine our Go test result from them.
           test_go_results=$(tr -d '\n' <<< '${{ toJSON(needs.*.result) }}' | jq -Mrc)
           if ! grep -q -v -E '(failure|cancelled)' <<< "$test_go_results"; then
+            test_go_result="failed"
+            result="failed"
+          else
+            test_go_result="success"
+          fi
+
+          # If we have downloaded data race detector logs then at least one Go test job detected
+          # a data race during execution. We'll fail on that.
+          if [ -z "$(ls -A data-race-logs)" ]; then
+            data_race_output=""
+            data_race_result="success"
+          else
+            data_race_output="$(cat data-race-logs/*)"
+            data_race_result="failed"
             result="failed"
           fi
-          data_race_output=""
-          data_race_results=$(tr -d '\n' <<< '${{ toJSON(needs.test-go.outputs.data-race-result) }}' | jq -Mrc)
-          if ! grep -q -v -E '(failure|cancelled)' <<< "$data_race_results"; then
-            data_race_output="${{ toJSON(needs.test-go.outputs.data-race-output) }}"
-            result="failed"
-          fi
+
+          # Write Go and data race results to outputs.
           {
             echo "data-race-output=${data_race_output}"
-            echo "data-race-results=${data_race_results}"
+            echo "data-race-result=${data_race_result}"
             echo "result=${result}"
+            echo "test-go-result=${test_go_result}"
             echo "test-go-results=${test_go_results}"
           } | tee -a "$GITHUB_OUTPUT"
       # Aggregate, prune, and cache our timing data
@@ -611,7 +662,7 @@ jobs:
           pattern: ${{ needs.test-go.outputs.go-test-results-download-pattern }}
           merge-multiple: true
       - if: ${{ ! cancelled() && needs.test-go.result == 'success' && inputs.test-timing-cache-enabled }}
-        name: Prune old timing
+        name: Prune any invalid timing files
         run: |
           ls -lhR '${{ needs.test-matrix.outputs.go-test-dir }}'
           find '${{ needs.test-matrix.outputs.go-test-dir }}' -mindepth 1 -type f -mtime +3 -delete
@@ -623,7 +674,7 @@ jobs:
           ' shell {} \; > /dev/null 2>&1
 
           ls -lhR '${{ needs.test-matrix.outputs.go-test-dir }}'
-      # Determine our overall pass/fail with our Go test results and our
+      # Determine our overall pass/fail with our Go test results
       - if: always() && steps.status.outputs.result != 'success'
         name: Check for failed status
         run: |
